### ISSUE TITLE
Zooming glitches

### ISSUE THREAD

**Issue by winkler1** [react-d3/react-d3-map#6]
Hi-
 When zooming in using the mouse wheel, there are flashes of maps at the wrong resolution. http://screencast.com/t/5pPF5IO5

**Comment by chilijung** [comment]
Hi @winkler1, thanks for reporting this problem, I'll working to solve this soon.
The reason of the flashes is the map updating it's tiles during the whole zooming process, so the tile maps keep cleaning up the old tiles and replace the new one.

**Comment by chilijung** [comment]
hi @winkler1 !! I fixed this problem at react-d3-map@0.2.0 !! :+1:

**Comment by winkler1** [comment]
:+1:
